name: PR Security Scan

on:
  pull_request:
    branches: [ main ]

permissions:
  pull-requests: write
  contents: read

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: git fetch origin main

      - name: Run Semgrep Scan
        uses: returntocorp/semgrep-action@v1
        with:
          entryPoint: semgrep
          args: --config p/ci --baseline-commit=origin/main -metrics=off --github-pr-comments

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}